.Dd September 08, 2019
.Dt NOTE_GETHEADER
.Os
.Sh NAME
.Fn Note_GetHeader
.Nd Get a note's header.
.Sh SYNOPSIS
.Sy #include <libnotes.h>
.Pp
.Fn "size_t Note_GetHeader" "struct Note *note" "char *buff" "size_t buff_size"

.Sh DESCRIPTION
The function
.Fn Note_GetHeader
gets the header from an already-opened note, pointed to by
.Fa note ,
and puts it in the buffer
.Fa buff
of size
.Fa buff_size .
If
.Fa buff
is NULL then
.Fa buff_size
is ignored and it allows you to get the size of the header.

.Sh RETURN VALUE
.Fn Note_GetHeader
returns the number of bytes written into buff, which is equal to or less than
.Fa buff_size . On an error it returns 0 and
.Em errno
is set for any of the errors specified for
.Xr read 3

.Sh CONFORMING TO
This does not conform to, or implement, any standard.

.Sh SEE ALSO
.Xr Note_GetBody 3
.Xr Note_GetLock 3
.xr read 3

.Sh AUTHORS
Sapeint/Chanku
